language: java
jdk:
  - oraclejdk8
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - mvn -f dev/project/pom.xml clean install
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r dev/project/common/target/site/jacoco-ut/jacoco.xml
  - bash <(curl -s https://codecov.io/bash) -t 65a321bf-8e09-4f46-a747-8e0d57259732
