language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install
  - mvn test
  - mvn clean verify