language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - mvn -f dev/project/pom.xml clean install