language: java
jdk:
  - oraclejdk8
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - mvn -f dev/project/pom.xml clean install
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 65a321bf-8e09-4f46-a747-8e0d57259732
