package utils.properties;

public enum Property
{
	//Project properties
	PREDICTION_PRINTING,
	PREDICTION_FILE_SAVE_PATH,
	SHOULD_DOWNLOAD_ALL_ISSUES,
	//Hibernate properties
	HIBERNATE_DRIVER_CLASS,
	HIBERNATE_USER,
	HIBERNATE_PASSWORD,
	HIBERNATE_DIALECT,
	HIBERNATE_SCHEMA_PRODUCTION,
	HIBERNATE_SCHEMA_TEST,
	//Issue similarity parameters
	SUMMARY_WEIGHT,
	DESCRIPTION_WEIGHT,
	COMMENTS_WEIGHT,
	K_SHINGLES,
	//model parameters
	MODEL_MIN_ALPHA, 
	MODEL_K, 
	//filter parameters
	FILTER_MIN_NUMBER_OF_ISSUES_FOR_DEVELOPER, 
	FILTER_MIN_DESCRIPTION_LONG_SIZE
}
