package utils.properties;

public enum Property
{
	PREDICTION_PRINTING,
	PREDICTION_FILE_SAVE_PATH,
	//Hibernate properties
	HIBERNATE_DRIVER_CLASS,
	HIBERNATE_USER,
	HIBERNATE_PASSWORD,
	HIBERNATE_DIALECT,
	HIBERNATE_SCHEMA_PRODUCTION,
	HIBERNATE_SCHEMA_TEST,
	//Issue similarity parameters
	SUMMARY_WEIGHT,
	DESCRIPTION_WEIGHT,
	COMMENTS_WEIGHT,
	//model parameters
	MODEL_MIN_ALPHA, 
	MODEL_K, 
	MIN_NUMBER_OF_ISSUES_FOR_DEVELOPER
}
