package utils.properties;

public enum Property
{
	//Project properties
	PREDICTION_PRINTING,
	PREDICTION_FILE_SAVE_PATH,
	SHOULD_DOWNLOAD_ALL_ISSUES,
	//Hibernate properties
	HIBERNATE_DRIVER_CLASS,
	HIBERNATE_USER,
	HIBERNATE_PASSWORD,
	HIBERNATE_DIALECT,
	HIBERNATE_SCHEMA_PRODUCTION,
	HIBERNATE_SCHEMA_TEST,
	//project parameters
	PROJECT_URL,
	PROJECT_KEY,
	PROJECT_NAME,
	PROJECT_ISSUE_LIMIT,
	PROJECT_ID_JIRA_ISSUE_TO_ANALYZE,
	//Issue similarity parameters
	SUMMARY_WEIGHT,
	DESCRIPTION_WEIGHT,
	INCLUDE_COMMENTS_SIMILARITY,
	COMMENTS_WEIGHT,
	K_SHINGLES,
	//model parameters
	MODEL_MIN_ALPHA,
	MODEL_MIN_SIGMA,
	K_RESULTS,
	//filter parameters
	FILTER_MIN_NUMBER_OF_ISSUES_FOR_DEVELOPER, 
	FILTER_MIN_DESCRIPTION_LONG_SIZE,
	FILTER_ISSUE_TYPE_LIST,
	FILTER_ISSUE_PRIORITY_LIST;
	
}
